# Generated by Django 5.2.6 on 2025-10-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altecplast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='lavage_jour_motif_arret1',
            field=models.CharField(blank=True, choices=[('arr_mp', 'Arrêt MP'), ('arr_mce', 'Arrêt Maintenance'), ('arr_ntt', 'Arrêt Nettoyage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='lavage_jour_motif_arret2',
            field=models.CharField(blank=True, choices=[('arr_mp', 'Arrêt MP'), ('arr_mce', 'Arrêt Maintenance'), ('arr_ntt', 'Arrêt Nettoyage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='lavage_nuit_motif_arret1',
            field=models.CharField(blank=True, choices=[('arr_mp', 'Arrêt MP'), ('arr_mce', 'Arrêt Maintenance'), ('arr_ntt', 'Arrêt Nettoyage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='lavage_nuit_motif_arret2',
            field=models.CharField(blank=True, choices=[('arr_mp', 'Arrêt MP'), ('arr_mce', 'Arrêt Maintenance'), ('arr_ntt', 'Arrêt Nettoyage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='prealpina_jour_motif_arret1',
            field=models.CharField(blank=True, choices=[('arr_mp', 'Arrêt MP'), ('arr_mce', 'Arrêt Maintenance'), ('arr_ntt', 'Arrêt Nettoyage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='prealpina_jour_motif_arret2',
            field=models.CharField(blank=True, choices=[('arr_mp', 'Arrêt MP'), ('arr_mce', 'Arrêt Maintenance'), ('arr_ntt', 'Arrêt Nettoyage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='prealpina_nuit_motif_arret1',
            field=models.CharField(blank=True, choices=[('arr_mp', 'Arrêt MP'), ('arr_mce', 'Arrêt Maintenance'), ('arr_ntt', 'Arrêt Nettoyage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='prealpina_nuit_motif_arret2',
            field=models.CharField(blank=True, choices=[('arr_mp', 'Arrêt MP'), ('arr_mce', 'Arrêt Maintenance'), ('arr_ntt', 'Arrêt Nettoyage')], max_length=20, null=True),
        ),
    ]
