[project]
name = "altecplast"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "gunicorn>=23.0.0",
    "openpyxl>=3.1.5",
]
